### PR TITLE
Refactored to use common Mil2525CMessageParser

### PR DESCRIPTION
**Pull request by garys-esri**

### CODE REVIEW

**Comment by csmoore** [comment]
Testing this now - do we have any GeoMessage files in the new area of interest (Monterey)? 

I [looked here](https://github.com/Esri/geomessage-simulator-qt/tree/master/source/geomessage-simulator/SampleMessages) but not sure where else to look.

**Comment by csmoore** [comment]
I tested this with an old geomessage dataset - this is ready to merge unless you want me to test against a geomessage set in the current area of interest.

**Comment by garys-esri** [comment]
Let's merge it then. There is a Monterey message file at https://github.com/Esri/vehicle-commander-java/blob/master/data/coa.xml if you do want to check it. There's a much larger one at  https://github.com/Esri/geomessage-simulator-qt/blob/master/GeoMessageSpecification/sample-messages/MontereySimulation500x100.xml that's meant more for the simulator than for a message layer, but in theory it should work, given enough RAM.

**Comment by csmoore** [comment]
[MontereySimulation500x100.xml](https://github.com/Esri/geomessage-simulator-qt/blob/master/GeoMessageSpecification/sample-messages/MontereySimulation500x100.xml) Works fine - thanks

image

**Comment by garys-esri** [comment]
Yes, I forgot that it was 100 symbols with 500 movements (or maybe the other way around), not 100x500 symbols. Thanks!

**Pull request merged**
